import { test, expect } from "vitest";
import { div, p } from "../src/autoGeneratedTags.js";

test("create div with attributes and children", () => {
  const d = div({ id: "container" }, [
    p({}, ["Hello, World!"]),
    "Plain text child",
  ]);

  expect(d.tagName).toBe("DIV");
  expect(d.getAttribute("id")).toBe("container");
  expect(d.children.length).toBe(1); // The <p> element
  expect(d.childNodes.length).toBe(2); // The <p> element and the text node
});
